# Created at 2020-01-27T09:40:16.719
TestSet has not finished before stream error has appeared >> initializing exit by non-null configuration: null
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
	at org.apache.maven.surefire.booter.MasterProcessCommand.decode(MasterProcessCommand.java:115)
	at org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:391)
	at java.base/java.lang.Thread.run(Thread.java:834)


# Created at 2020-01-27T09:40:16.832
Unexpected IOException with stream: 2020-01-27 09:40:16.831  INFO 72448 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...


# Created at 2020-01-27T09:40:20.139
Unexpected IOException with stream: 2020-01-27 09:40:20.137  INFO 72448 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.


# Created at 2020-01-27T09:40:20.162
Unexpected IOException with stream: 2020-01-27 09:40:20.161  INFO 72448 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect


# Created at 2020-01-27T09:40:46.450
Unexpected IOException with stream: 2020-01-27 09:40:46.446  INFO 72448 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]


# Created at 2020-01-27T09:40:46.464
Unexpected IOException with stream: 2020-01-27 09:40:46.463  INFO 72448 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'


# Created at 2020-01-27T09:40:47.195
Unexpected IOException with stream: 2020-01-27 09:40:47.192  WARN 72448 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning


# Created at 2020-01-27T09:40:47.504
Unexpected IOException with stream: 2020-01-27 09:40:47.503  INFO 72448 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'


# Created at 2020-01-27T09:40:47.964
Unexpected IOException with stream: 2020-01-27 09:40:47.963  INFO 72448 --- [           main] c.c.u.skybook.SkybookApplicationTests    : Started SkybookApplicationTests in 33.578 seconds (JVM running for 34.687)


# Created at 2020-01-27T09:40:47.991
Unexpected IOException: 5,1,com.capgemini.uraan.skybook.SkybookApplicationTests,contextLoads,null,null,null


# Created at 2020-01-27T09:40:48.123
Unexpected IOException: 6,1,com.capgemini.uraan.skybook.SkybookApplicationTests,contextLoads,null,null,null


# Created at 2020-01-27T09:40:48.127
Unexpected IOException: 2,1,org.apache.maven.surefire.junitplatform.JUnitPlatformProvider,com.capgemini.uraan.skybook.SkybookApplicationTests,null,null,null


